Traceback (most recent call last):
  File "C:\Users\garys\OneDrive\Python\Courses\Automate the Boring Stuff with Python\Section12\raise_assert.py", line 26, in <module>
    raise Exception("This is the error message")
Exception: This is the error message
